language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install black
  - python3.7 -m pip install flake8
  - pip install pyyaml
  - pip install coveralls
scripts:
  - black .
  - flake8 .
  - coverage run manage.py test
after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "hCWspKUd+CoWIhg3B7ppRm13ffNNwP3OHmBUjYi4toBJz4ZeAJC9KIi9n9wb1l0JMm0RXdzcgNG4aSgwL2QU/BtbNwOWNfXmQSDwErLwxl703y25IE1KieEn2In8bcPwlbAvKNdhqKSVcrSRViraE/jGDI1SZzf4xj+8bhq1qRLx63cFz9lRMXP+HO6Drngsg8TILwlMANwWC8Eg/YbfgzTmM6l/mvzeuoYWmeFlCTvgt9GXZGUsQtGhAONyd0QmXTbnygpd2aqvZe2vAjP9nSbttlA8LQANizpW0aJqy+A4RZHZ80iqHWRipEIOF+GfJjVhiYpuL2gPpXYvqIi22Qv5uZU8P06TCZXDOpKrHM9/cMTvStGwRzN50LiTpMORWJBtl8gmbVDJvtSN1V4/SOO4xwwdTMr+nyrrVu7HSAMjx+xJrzcbHjpgJu6KG2We5UtPB6X2htuW3an6zSd9fdAUE7a3oyN0kM7SmSUR9eKe8g+JqSwirYDh+4RfS4/CJjwJDFPzu25OPTzVTRvllA/STLLJxNP7iWIt1umor6vA+xO+Ce2Uzat/x12F7/fIO6bZKw9xSVK/UvxrBBUv0CYDF1nLm9IphMXmwhJkL2KZ0zjUrQprBpKspw4rNGtwMyo8jBDUPd/qA6K28B5D28ZV5anj5jQ2+9u13Ree6kM="
  secret_access_key:
    secure: "EiJXyH2tQjwK+wib0C7fE9H93fcWq7EpQ+TC7hdy6sEF3pPW7j28cNpKnHQTcHRzz4t0GIBS3+p2njekd4d30NMFwD1SuhtdUbfAu3gQl3UurWVkh6qcZmES8DEo6/RVS0n3jrOOQpm5Df1Ym3cqxTuZie5lUpiXubKKzpXpnCyCY1AIY2KVykqkdQBafi0CsI1Vukaf2SFE5Hin/fQBwlU6t5VlKJAenEErlF9JQY1EJevybGyE9WKNkvWkGFkPN9dxC8cfpM9FEf2Mr7yCixYiK932MjXRXPPKIVcUlZ5mzXDYuCU6nbd24LLgAexTgoiOVJNpbK5lLdE8zzfniiFxZKrD+vygRqM8VYvG+ExUVC6TziPXhSDKa4ooGFUyEq754sDLuuCqUL5IDb9u66QQDL8hUVlapCKUxcIey7t6oBJqix/iGpzkqoNNDv9K6OO2uqpeKBpyxHVXTBkS8vV9H468e+C/nKLcGLIRPFnWaZdnvIykn+jEPBRLkvtnZgccjZs4IaaD3kArMH0wz3ZOcW7Tn5AkDqzBuZBi0T6s/RgPCHMcxgc5k4pv6g8vjoBuQAHHtxWgVq1YyxrjbGSH3Kx0bRLJ56t3hn0GO+hcCYhIxoX37VaDJV9/twN6cWm7VFNg1w4z8/HhTUZSLICvgMiBWq3wlLwkXZEruPY="
  region: "us-west-2"
  app: "django-tutorial3"
  env: "django-env3"
  on:
    branch: main
  bucket_name: "elasticbeanstalk-us-west-2-989283189170"
